controllers:
    resource:
        path: ../src/Shared/Infrastructure/Controller
        namespace: App/Shared/Infrastructure/Controller
    type: attribute

#app.swagger:
#    path: /api/doc
#    methods: GET
#    defaults: {_controller: nelmio_api_doc.controller.swagger_ui}